C *********************************************************************
C
       SUBROUTINE reset_nbas
C
C  ORIGINALLY WRITTEN BY MARK R PEDERSON (1985), modified by Arlin Briley,
C  Dirk Porezag and God knows who else
C  CALLS TO REWRITE/INITZE REMOVED BY MRP 4-Feb 1998
C
C  MODE=1   CALCULATE OVERLAPS                -STORE IN HSTOR(I,1)
C  MODE=2   CALCULATE HAMILTONIAN             -STORE IN HSTOR(I,2)
C  MODE=3   CALCULATE KINETIC+NONLOCAL EOP    -STORE IN HSTOR(I,1)
C  MODE=4   CALCULATE KINETIC EOP             -STORE IN HSTOR(I,1)
C  EOP IS ABBREVIATION FOR ENERGY OPERATOR
C
       INCLUDE 'PARAMS'
       INCLUDE 'commons.inc'
       CHARACTER*7 FNAME
       LOGICAL FIRST,OVLBABY,HAMBABY,HNLBABY,KINBABY,STARTUP
       DIMENSION NDEG(3),AI(3),AJ(3),IPOINT(MAX_REP)
       DIMENSION SS(10,10)
       DIMENSION RNUCI(3,MX_GRP),RNUCJ(3,MX_GRP)
       DIMENSION IBEG(3),IEND(3)
       DIMENSION IND_SALC(ISMAX,MAX_CON,3,2)
       DIMENSION LNDX(6,MAX_CON,3,2)
       DIMENSION RNUC(3,MX_GRP),MSITES(1)
       DATA NDEG/1,3,6/
       DATA IBEG,IEND/1,2,5,1,4,10/
C
C CHECK AND PRINT BASIS SET PROPERTIES
C
        NORBS=0
        NBSMAX=0
        WRITE(7,*) ' '
        WRITE(7,*) ' SUMMARY OF BASIS SET:'
        WRITE(7,*) ' NUMBER OF CONTRACTED FUNCTION SETS:',NFNCT
        IID=0
        DO 10 IFNCT=1,NFNCT
         NSITE=0
         WRITE(7,*) ' '
         WRITE(7,*) ' FUNCTION SET:',IFNCT
         DO IPOS=1,N_POS(IFNCT)
          IID=IID+1
          CALL GASITES(1,RIDT(1,IID),MNUC,RNUC,MSITES)
          NSITE=NSITE+MNUC
          WRITE(7,1010) IFNCT,IPOS,(RIDT(I,IID),I=1,3)
 1010     FORMAT(' FS:',I3,' IP:',I3,' POSITION:',3F15.6)
         END DO
         WRITE(7,*) 'CONTRACTED ORBITALS FOR ANGULAR TYPE S:',
     &               N_CON(1,IFNCT)
         WRITE(7,*) 'CONTRACTED ORBITALS FOR ANGULAR TYPE P:',
     &               N_CON(2,IFNCT)
         WRITE(7,*) 'CONTRACTED ORBITALS FOR ANGULAR TYPE D:',
     &               N_CON(3,IFNCT)
         WRITE(7,*) 'GAUSSIANS FOR FUNCTION SET:'
         WRITE(7,1020)(BFALP(I,IFNCT),I=1,N_BARE(IFNCT))
 1020    FORMAT(' ',7G11.3)
         NADD=N_CON(1,IFNCT)+3*N_CON(2,IFNCT)+6*N_CON(3,IFNCT)
         NORBS=NORBS+NADD*NSITE
         NBSMAX=MAX(NBSMAX,NADD)
         DO L=0,LSYMMAX(IFNCT)
          WRITE(7,*) 'CONTRACTED ORBITALS FOR ANGULAR MOMENTUM:',L
          DO ICON=1,N_CON(L+1,IFNCT)
           WRITE(7,1020)(BFCON(I,ICON,L+1,IFNCT),I=1,N_BARE(IFNCT))
          END DO
         END DO
   10   CONTINUE
        WRITE(7,*) 'TOTAL NUMBER OF CONTRACTED ORBITALS:',NORBS
        WRITE(7,*) ' '
        IF (IID.NE.NIDENT) THEN
         PRINT *,'OVERLAP: IID AND NIDENT ARE DIFFERENT: ',IID,NIDENT
         CALL STOPIT
        END IF
        IF (NBSMAX.GT.MAXUNSYM) THEN 
         PRINT *,'OVERLAP: MAXUNSYM MUST BE AT LEAST: ',NBSMAX
         CALL STOPIT
        END IF
C
C INITITIALIZE SALC INDICES
C
        DO KREP=1,N_REP
         INDBEG(1,KREP)=0
         NS_TOT(KREP)  =0
        END DO
        DO 20 IID=1,NIDENT
         IFNCT=IFUIDT(IID)
         CALL OBINFO(1,RIDT(1,IID),RNUC,MNUC,ISHELL)
         CALL GSMAT(ISHELL,2)
         KSALC=0
         DO KREP=1,N_REP
          KSALC=KSALC+NDMREP(KREP)
          DO L=0,LSYMMAX(IFNCT)
           NS_TOT(KREP)=NS_TOT(KREP)
     &                 +N_CON(L+1,IFNCT)*N_SALC(KSALC,L+1,ISHELL)
          END DO
          IF (IID .NE. NIDENT) INDBEG(IID+1,KREP)=NS_TOT(KREP)
         END DO
   20   CONTINUE
C
C SQUISHING TO SINGLE INDICES
C
        NHTOT=0
        DO KREP=1,N_REP
         IPOINT(KREP)=NHTOT
         NHTOT=NHTOT+(NS_TOT(KREP)*(NS_TOT(KREP)+1))/2
         IF (NS_TOT(KREP).GT.NDH) THEN
          PRINT *,'OVERLAP: NDH MUST BE AT LEAST: ',NS_TOT(KREP)
          CALL STOPIT
         END IF
        END DO
        IF (NHTOT.GT.NDH_TOT) THEN
         PRINT*,'OVERLAP: NDH_TOT MUST BE AT LEAST: ',NHTOT
         CALL STOPIT
        END IF
C
C CHECK IF MTEMP IS LARGE ENOUGH
C
        MTMAX=0
        DO 40 IID=1,NIDENT
         DO JID=IID,NIDENT
          KOUNT=0
          DO KREP=1,N_REP
           IF (IID.EQ.NIDENT) THEN
            MI=NS_TOT(KREP)-INDBEG(IID,KREP)
           ELSE
            MI=INDBEG(IID+1,KREP)-INDBEG(IID,KREP)
           END IF
           IF (JID.EQ.NIDENT) THEN
            MJ=NS_TOT(KREP)-INDBEG(JID,KREP)
           ELSE
            MJ=INDBEG(JID+1,KREP)-INDBEG(JID,KREP)
           END IF
           KOUNT=KOUNT+MI*MJ
          END DO
          MTMAX=MAX(KOUNT,MTMAX)
         END DO
   40   CONTINUE
        IF (MTMAX.GT.MTEMP) THEN
         PRINT *,'OVERLAP: MTEMP MUST BE AT LEAST: ',MTMAX
         CALL STOPIT
         ENDIF

        RETURN
        END
