SUBROUTINE LOWDIN_DIAGONALIZE(HAM, OVER, NBAS, EVAL, SC1, LWORK, INFO)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NBAS, LWORK
  DOUBLE PRECISION, INTENT(INOUT) :: HAM(NBAS,NBAS), OVER(NBAS,NBAS)
  DOUBLE PRECISION, INTENT(OUT) :: EVAL(NBAS), SC1(LWORK)
  INTEGER, INTENT(OUT) :: INFO

  DOUBLE PRECISION :: D(NBAS), U(NBAS,NBAS), S_INV_SQRT(NBAS,NBAS)
  DOUBLE PRECISION :: TMP(NBAS,NBAS)
  INTEGER :: I, J, K
  DOUBLE PRECISION, PARAMETER :: EPS = 1.0D-8

  ! Step 1: Diagonalize OVER = U D U^T
  U(:,:) = OVER(:,:)
  CALL DSYEV('V', 'L', NBAS, U, NBAS, D, SC1, LWORK, INFO)
  IF (INFO .NE. 0) THEN
    PRINT *, 'DSYEV failed on OVER: INFO =', INFO
    RETURN
  END IF

  ! Step 2: Build S^{-1/2} = U * D^{-1/2} * U^T
  DO I = 1, NBAS
    IF (D(I) > EPS) THEN
      D(I) = 1.0D0 / SQRT(D(I))
    ELSE
      D(I) = 0.0D0
    END IF
  END DO

  ! S_INV_SQRT = U * D^{-1/2} * U^T
  DO I = 1, NBAS
    DO J = 1, NBAS
      S_INV_SQRT(I,J) = 0.0D0
      DO K = 1, NBAS
        S_INV_SQRT(I,J) = S_INV_SQRT(I,J) + U(I,K)*D(K)*U(J,K)
      END DO
    END DO
  END DO

  ! Step 3: H_ortho = S^{-1/2} * HAM * S^{-1/2}
  CALL DGEMM('N','N', NBAS, NBAS, NBAS, 1.0D0, S_INV_SQRT, NBAS, HAM, NBAS, 0.0D0, TMP, NBAS)
  CALL DGEMM('N','N', NBAS, NBAS, NBAS, 1.0D0, TMP, NBAS, S_INV_SQRT, NBAS, 0.0D0, HAM, NBAS)

  ! Step 4: Diagonalize H_ortho
  CALL DSYEV('V','L', NBAS, HAM, NBAS, EVAL, SC1, LWORK, INFO)
  IF (INFO .NE. 0) THEN
    PRINT *, 'DSYEV failed on H_ortho: INFO =', INFO
    RETURN
  END IF

END SUBROUTINE LOWDIN_DIAGONALIZE
