        SUBROUTINE VMESH(ITBEG,ICALC)
        INCLUDE 'PARAMS'
C
C MXRZON: MAX. NUMBER OF RADIAL ZONES FOR ATOMIC SPERES
C MXTYP:  MAX. NUMBER OF DIFFERENT ATOM TYPES
C MXCUBE: MAX. NUMBER OF CUBES
C MXONED: MAX. NUMBER OF POINTS FOR ONE-DIMENSIONAL MESH
C MXRAD:  MAX. NUMBER OF POINTS FOR A RADIAL MESH
C MXCPTS: MAX. NUMBER OF INEQIV. POINTS FOR AN ATOMIC CUBE
C MXANG:  MAX. NUMBER OF ANGULAR POINTS FOR AN ATOMIC SPHERE
C KILO:   BUFFER SPACE
C
        PARAMETER (MXRZON=5)
        PARAMETER (MXTYP=5)
        PARAMETER (MXCUBE=1000)
        PARAMETER (MXONED=100)
        PARAMETER (MXRAD=4*MXONED)
        PARAMETER (MXCPTS=400)
        PARAMETER (MXANG=200)
        PARAMETER (KILO=10000)
        LOGICAL INBOX,CATOM,EXIST,OK,OKXYZ,FIXIT,LREPAIR,LSYWT
        LOGICAL ISOLATED
        COMMON/PERIODIC/XBND(2,3),TVEC(4,3),NPER
        COMMON/ACUTS/ALPMN,ALPMX,ACUT,ACCUR
        COMMON/GROUP/RMAT(3,3,MX_GRP),NGRP
        COMMON/MESHN/DV(2,MAX_PTS)
        COMMON/MESH/DVV(1,MAX_PTS),R(3,MAX_PTS),NPTS
        COMMON/BASET/ZELC(MAX_FUSET),ZZNUC(MAX_FUSET)
     &   ,CON(MAX_BARE,MAX_CON,LDIM,MAX_FUSET)
     &   ,ALPH(MAX_BARE,MAX_FUSET)
        COMMON/INTBASET/N_BARE(MAX_FUSET),N_CON(LDIM,MAX_FUSET)
     &   ,LSYMMAX(MAX_FUSET),N_POS(MAX_FUSET),NFNCT
        COMMON/NUCLEI/RIDT(3,MAX_IDENT),IFUSET(MAX_IDENT),NNIDENT      
C
C SCRATCH COMMON BLOCK FOR LOCAL ARRAYS
C
        COMMON/TMP1/BCUT(3,MX_CNT+8),PLANE(2,3,MXCUBE)
     &   ,SIDE(2,3,MXCUBE),XSLICE(3*MX_CNT),XSEP(MX_CNT+2)
     &   ,ZTEST(27*MX_CNT),RSQR(KILO),RSQVOL(2,MXCUBE)
     &   ,BOXMOL(3,2),ZNUC(27*MX_CNT),ALTAB(MAX_BARE)
     &   ,NCON(3),NXPT(3),ICLOSE(MAX_PTS),ISLICE(3*MX_CNT)
     &   ,NUMBOX(MXCUBE)
     &   ,NFBUF(8),NSYMOP(MX_GRP),NORIG(MXCUBE)
     &   ,CATOM(MXCUBE)
C
        DIMENSION RBUF(3,MXCPTS),WBUF(MXCPTS)
     &   ,RX(MXRAD),RY(MXONED),RZ(MXONED)
     &   ,WX(MXRAD),WY(MXONED),WZ(MXONED)
     &   ,ZZON(MXTYP),RZON(MXRZON)
     &   ,BOX(2,3),ANGLE(3,MXANG),DOMEGA(MXANG)
     &   ,RNUC(3,MX_CNT*27),RIDENT(3,MX_GRP),NPOW(27*MX_CNT)
     &   ,CIDENT(3,MX_CNT),CUBE(3,MXCUBE),NPATS(MXTYP),NPISS(MXTYP)
     &   ,LMXA(MXRZON,MXTYP),NPHI(MXTYP),NTHET(MXTYP),OKXYZ(3)
     &   ,TVC(3,3),TV(3)
        DIMENSION NLOOP(3)
C
        SAVE
        DATA LSYWT/.FALSE. /
        DATA ERRAT,FACZ2,AFUDAT/1.0D-6, 1000.0D0, 1.2D0/
        DATA NRZONE/5/
        DATA RZON/  0.1D0,  0.2D0, 0.5D0, 1.0D0,1000.0D0/
        DATA NTYP/  3/
        DATA ZZON/ 2.1D0, 18.1D0, 0.0D0, 0.0D0, 0.0D0/
        DATA NPATS/0, 2, 4, 0, 0/
        DATA NPISS/0, 0, 0, 0, 0/
        DATA NTHET/3, 3, 3, 0, 0/
        DATA NPHI/ 4, 4, 5, 0, 0/
        DATA LMXA/ 3,5,7,9,15,   3,5,7,11,15,
     &             5,7,9,15,15,  5*0,  5*0/
        DATA ERRIS,AFUDIS/1.0D-5, 1.2D0/
        DATA CUTFAC,MX1D/0.2D0, 8/
C
C RPILE IS THE ALLOWED RADIUS FOR A COLLECTION OF MESH POINTS
C THAT ARE SUPPOSED TO BE CLOSE TO EACH OTHER IN MEMORY.
C TOLER IS A GENERAL ACCURACY MARGIN.
C VOLTL IS THE VOLUME ACCURACY MARGIN.
C NTCEL IS THE NUMBER OF CELLS TO INCLUDE IN THE TOTAL CHARGE TEST
C
        DATA RPILE/2.0D0/
        DATA TOLER/1.0D-5/
        DATA VOLTL/1.0D-10/

        PRINT *,NNIDENT,'NNIDENT'
        IF (NNIDENT.LT.1) STOP
C
C CHECK IF VMOLD EXISTS AND READ MESHDAT IF AVAILABLE
C
        PRINT*,'START OF VMESH: ',ITBEG,ICALC
        IF(ITBEG.NE.0)THEN
         IF(ITBEG.LT.0)ITBEG=0
         INQUIRE(FILE='VMOLD',EXIST=EXIST)
         IF(EXIST)THEN
          OPEN(99,FILE='VMOLD',FORM='UNFORMATTED',STATUS='UNKNOWN')
          REWIND(99)
          READ(99)NPTS,JCALC
          IF(JCALC.NE.ICALC)THEN
           EXIST=.FALSE.
          ELSE
           READ(99)(( R(J,I),J=1,3),I=1,NPTS)
           READ(99)((DV(J,I),J=1,1),I=1,NPTS)
                 DO I=1,NPTS
                 DVV(1,I)=DV(1,I)
                 END DO
          END IF
          CLOSE(99)
          GOTO 900
         END IF
        END IF
        PI=4*ATAN(1.0D0)
C
C DEFINE MINIMUM/MAXIMUM ALPHA
C
         ALMIN=1.0D30
         ALMAX=0.0D0
         DO IFN=1,NFNCT
          ALMIN=MIN(ALMIN,ALPH(N_BARE(IFN),IFN))
          ALMAX=MAX(ALMAX,ALPH(1,IFN))
         ENDDO
C        PRINT*,'VMESH ALMIN : ',ALMIN
        IF (ALMIN .LT. 1.0D-3) ALMIN= 1.0D-3
        A1AT= ALMIN
        A1IS= ALMIN                         
        ALPMN= ALMIN
        ALPMX= ALMAX
C
C READ MESHDAT
C
        OPEN(99,FILE='MESHDAT',FORM='FORMATTED',STATUS='UNKNOWN')
        REWIND(99)
        READ(99,*,END=10)LSYWT
        READ(99,*,END=10)ERRAT,FACZ2,AFUDAT
        READ(99,*,END=10)NRZONE
        IF(NRZONE.GT.MXRZON)THEN
         PRINT *,'VMESH: MXRZON MUST BE AT LEAST: ',NRZONE
         STOP
        END IF
        READ(99,*,END=10)(RZON(IRZ),IRZ=1,NRZONE-1)
        RZON(NRZONE)=1000.0D0
        READ(99,*,END=10)NTYP
        IF(NTYP.GT.MXTYP)THEN
         PRINT *,'VMESH: MXTYP MUST BE AT LEAST: ',NTYP
         STOP
        ELSE IF(NTYP.LT.1)THEN
         PRINT *,'VMESH: NTYP IS < 1'
         STOP
        END IF
        IF(NTYP.GT.1)THEN
         READ(99,*,END=10)(ZZON(ITYP),ITYP=1,NTYP-1)
        END IF
        DO ITYP=1,NTYP
         READ(99,*,END=10)NPATS(ITYP),NPISS(ITYP),NTHET(ITYP),
     &             NPHI(ITYP),(LMXA(IRZ,ITYP),IRZ=1,NRZONE)          
        END DO
        READ(99,*,END=10)ERRIS,AFUDIS
        READ(99,*,END=10)CUTFAC,MX1D
        IF(MX1D.GT.MXONED)THEN
         PRINT *,'VMESH: MX1D MUST BE AT LEAST: ',MXONED
         STOP
        END IF
   10   CONTINUE
        RZON(NRZONE)=1000.0D0
        IF(AFUDAT .LT. 1.01D0)AFUDAT=1.2D0
        IF(AFUDIS .LT. 1.01D0)AFUDIS=1.2D0
C
C WRITE MESHDAT
C
        REWIND(99)
        WRITE(99,'(1X,L5)')LSYWT
        WRITE(99,'(3(1X,G12.5))')ERRAT,FACZ2,AFUDAT
        WRITE(99,'(1X,I3)')NRZONE
        WRITE(99,'(5(1X,G12.5))')(RZON(IRZ),IRZ=1,NRZONE-1)
        WRITE(99,'(1X,I3)')NTYP
        IF(NTYP.GT.1)THEN
         WRITE(99,'(5(1X,G12.5))')(ZZON(ITYP),ITYP=1,NTYP-1)
        END IF
        DO ITYP=1,NTYP
         WRITE(99,'(20(1X,I3))')NPATS(ITYP),NPISS(ITYP),NTHET(ITYP),
     &             NPHI(ITYP),(LMXA(IRZ,ITYP),IRZ=1,NRZONE)          
        END DO
        WRITE(99,'(2(1X,G12.5))')ERRIS,AFUDIS
        WRITE(99,'(1X,G12.5,1X,I3)')CUTFAC,MX1D
        WRITE(99,*)'------------------------------------------------'
        WRITE(99,*)'* LSYWT'
        WRITE(99,*)'* ERRMAX, FACZ2, ALFUDGE FOR ATOMIC CUBES'
        WRITE(99,*)'* NUMBER OF RADIAL MESHES INSIDE ATOM SPHERES'
        WRITE(99,*)'* OUTER RADII OF SPHERE ZONES'
        WRITE(99,*)'* NUMBER OF ATOM TYPES (NTYP)'
        WRITE(99,*)'* UPPER NUCLEAR CHARGE LIMIT FOR EACH ATOM TYPE'
        WRITE(99,*)'* NPATS, NPISS, NTHET, NPHI, LMAX FOR'
        WRITE(99,*)'  EACH RADIAL ZONE (NTYP LINES)'
        WRITE(99,*)'* INTERSTITIALS: ERRMAX, ALFUDGE'
        WRITE(99,*)'* CUTFAC, MAX. NUMBER OF POINTS IN A'
        WRITE(99,*)'  ONE-DIMENSIONAL INTERSTITIAL PARTITION'
        CLOSE(99)
C
C CHECK ORDERING OF RZON AND ZZON
C
        DO IRZ=2,NRZONE-1
         IF(RZON(IRZ).LT.RZON(IRZ-1))THEN
          PRINT *,'VMESH: ORDER RZON IN MESHDAT SMALL -> BIG'
          STOP
         END IF
        END DO
        DO ITYP=2,NTYP-1
         IF(ZZON(ITYP).LT.ZZON(ITYP-1))THEN
          PRINT *,'VMESH: ORDER ZZON IN MESHDAT SMALL -> BIG'
          STOP
         END IF
        END DO
C
C IF PERMUTATION MATRICES DO NOT APPEAR FIRST IN GRPMAT THEN STOP
C
        IF(NGRP.GT.MX_GRP)THEN
         PRINT *,'VMESH: MX_GRP MUST BE AT LEAST: ',NGRP
         STOP
        END IF
        OK=.TRUE.
        NGPERM=0
        DO 20 IGRP=1,NGRP
         ADD=0.0D0
         DO I=1,3
          DO J=1,3
           ADD=ADD+ABS(RMAT(J,I,IGRP))
          END DO
         END DO
         IF(ADD.LT.(3.0D0+TOLER))THEN
          NGPERM=NGPERM+1
          IF(.NOT.OK)THEN
           PRINT *,'VMESH: X/Y/Z PERMUTATION MATRICES MUST APPEAR'
           PRINT *,'FIRST IN GRPMAT. PLEASE REORDER.'
           STOP
          END IF
         ELSE
          OK=.FALSE.
         END IF
   20   CONTINUE
C
C CHECK IF WE HAVE TO ADD MORE IDENTITY MEMBERS 
C
        NGFULL=NGRP
        FIXIT=.FALSE.
C
C PERIODIC FIX: 
C
        PRINT*,'VMESH : ',NGRP,NGPERM,FIXIT
        IF(NGPERM.LT.NGRP)FIXIT=.TRUE.
C
C READ IN GAUSS. PRINT IDENTITY MEMBERS. SETUP SOME ARRAYS
C NCUBE IS TOTAL NUMBER OF CENTERS IN GAUSS, NIDENT IS THE 
C NUMBER OF CENTERS WITH NONZERO NUCLEAR CHARGE.
C
        NCUBE=NNIDENT
        IF(NCUBE.GT.MX_CNT)THEN
         PRINT *,'VMESH: MX_CNT MUST BE AT LEAST: ',NCUBE
         STOP
        END IF
        PRINT *,' '
        PRINT *,'ORIGINAL IDENTITY MEMBERS:'
        NIDENT=0
        DO 30 ICUBE=1,NCUBE
         NIDENT=NIDENT+1
         DO I=1,3
         CIDENT(I,NIDENT)=RIDT(I,ICUBE)
         ENDDO
         ZNUC(NIDENT)=ZZNUC(IFUSET(ICUBE))
         NORIG(NIDENT)=NIDENT
         PRINT *,'ATOM ',NIDENT,', Z= ',ZNUC(NIDENT)
         PRINT 8010,(CIDENT(I,NIDENT),I=1,3)
   30   CONTINUE
C
C CHECK TO SEE IF ANY MORE 'IDENTITIES' NEED TO BE ADDED IF
C USING A SMALLER GROUP 
C
        IF((NGFULL+NGPERM).GT.MXCUBE)THEN
         PRINT *,'VMESH: MXCUBE MUST BE AT LEAST: ',NGFULL+NGPERM
         STOP
        END IF
        NUNIQUE=NIDENT
        IF(FIXIT)THEN
         DO 60 ICUBE=1,NIDENT
          NGRP=NGFULL
          KFULL=MXCUBE
          CALL GASITES(3,CIDENT(1,ICUBE),KFULL,CUBE)
          NGRP=NGPERM
          KPERM=MXCUBE-KFULL
          CALL GASITES(3,CIDENT(1,ICUBE),KPERM,CUBE(1,KFULL+1))
C
C ADD IDENTITY MEMBERS
C
          IF(KPERM.LT.KFULL)THEN
           DO 50 JCUBE=1,KFULL
            EMIN=1.0D30
            DO KCUBE=1,KPERM
             ERROR=ABS(CUBE(1,KCUBE+KFULL)-CUBE(1,JCUBE))+
     &             ABS(CUBE(2,KCUBE+KFULL)-CUBE(2,JCUBE))+
     &             ABS(CUBE(3,KCUBE+KFULL)-CUBE(3,JCUBE))
             IF(ERROR.LT.EMIN)EMIN=ERROR
            END DO
            IF(EMIN.GT.TOLER)THEN
             NUNIQUE=NUNIQUE+1
             IF(NUNIQUE.GT.MX_CNT)THEN
              PRINT *,'VMESH: MX_CNT MUST BE AT LEAST: ',NCUBE
              STOP
             END IF
             CIDENT(1,NUNIQUE)=CUBE(1,JCUBE)
             CIDENT(2,NUNIQUE)=CUBE(2,JCUBE)
             CIDENT(3,NUNIQUE)=CUBE(3,JCUBE)
             ZNUC(NUNIQUE)=ZNUC(ICUBE)
             NORIG(NUNIQUE)=NORIG(ICUBE)
             PRINT 8020,'ADDED IDENT:',(CIDENT(J,NUNIQUE),J=1,3)
             KADD=MXCUBE-(KFULL+KPERM)
             CALL GASITES(3,CIDENT(1,NUNIQUE),
     &                    KADD,CUBE(1,KFULL+KPERM+1))
             KPERM=KPERM+KADD
             IF(KPERM.EQ.KFULL)GOTO 40
            END IF
   50      CONTINUE
           PRINT *,'VMESH: LOGICAL ERROR, BUG SUSPECTED'
           STOP
   40      CONTINUE
          END IF
   60    CONTINUE
        END IF
C
C SETUP NGRP, NNUC, CUBE, NORIG, ZNUC AND NPOW 
C FOR SPACE PARTITIONING. 
C 
        NGRP=NGPERM
        NNUC=0
        NPMAX=0
        DO 70 ICUBE=1,NUNIQUE
         IF((NNUC+NGPERM).GT.MXCUBE)THEN
          PRINT *,'VMESH: MXCUBE MUST BE AT LEAST: ',NNUC+NGPERM
          STOP
         END IF
         MSTART=NNUC+1
C
C GET ATOM TYPE, NPMAX
C
         ITYP=NTYP
         DO JTYP=NTYP-1, 1, -1
          IF(ZNUC(MSTART).LE.ZZON(JTYP))ITYP=JTYP
         END DO
         NPMAX=MAX(NPMAX,NPATS(ITYP))
         NPMAX=MAX(NPMAX,NPISS(ITYP))
C
C GET ALL EQUIVALENT ATOMS
C
         KCUBE=MXCUBE-MSTART
         CALL GASITES(3,CIDENT(1,ICUBE),KCUBE,CUBE(1,MSTART))
C
C MOVE NORIG AND ZNUC INFORMATION FOR FOLLOWING ATOMS TO A SAFE
C LOCATION. THEN, SET UP NPOW, NORIG AND ZNUC FOR EACH NEW CUBE
C
         IF((NNUC+KCUBE).GT.MX_CNT)THEN
          PRINT *,'VMESH: MX_CNT MUST BE AT LEAST: ',NNUC+KCUBE
          STOP
         END IF
         MSHIFT=KCUBE-1
         DO JCUBE=MSTART+NUNIQUE-ICUBE, MSTART+1, -1
          NORIG(JCUBE+MSHIFT)=NORIG(JCUBE)
          ZNUC(JCUBE+MSHIFT)=ZNUC(JCUBE)
         END DO
         DO JCUBE=MSTART,NNUC+KCUBE
          NPOW(JCUBE)=MAX(NPISS(ITYP),0)
          NORIG(JCUBE)=NORIG(MSTART)
          ZNUC(JCUBE)=ZNUC(MSTART)
          PRINT *,'JCUBE,NPOW,NORIG,ZNUC',JCUBE,NPOW(JCUBE),
     &             NORIG(JCUBE),ZNUC(JCUBE)
         END DO
         NNUC=NNUC+KCUBE
         IF (NNUC.GT.MX_CNT) THEN
          PRINT*,'VMESH: NNUC > MX_CNT'
          STOP
         END IF
   70   CONTINUE
        RINFTY= 0.1D0*ERRIS
        RINFTY= RCUTOFF(NPMAX,ALMIN,RINFTY)
        PRINT *,'RINFINITY SET TO: ',RINFTY
C 
C NNUC IS THE ACTUAL NUMBER OF SHELL CENTERS
C BOXMOL CONTAINS THE X/Y/Z BOUNDARIES OF THE MOLECULE
C
        PRINT *,' '
        PRINT *,'NUMBER OF UNIQUE ATOMS: ',NUNIQUE
        PRINT *,'COORDINATES OF ATOMIC CUBES:'
        DO I=1,3
         BOXMOL(I,1)=  1.0D30
         BOXMOL(I,2)= -1.0D30
        END DO
        DO 80 ICUBE=1,NNUC
         PRINT 8010,(CUBE(I,ICUBE),I=1,3)
         DO I=1,3
          RNUC(I,ICUBE)=CUBE(I,ICUBE)
          IF(CUBE(I,ICUBE).LT.BOXMOL(I,1)) BOXMOL(I,1)=CUBE(I,ICUBE)
          IF(CUBE(I,ICUBE).GT.BOXMOL(I,2)) BOXMOL(I,2)=CUBE(I,ICUBE)
         END DO  
   80   CONTINUE
C
C ADD RINFTY TO THE BOUNDARY BOX LIMITS AND GET EXPECTED VOLUME
C
        EXPECTED=1.0D0
        DO I=1,3
         BOXMOL(I,1)=BOXMOL(I,1)-RINFTY
         BOXMOL(I,2)=BOXMOL(I,2)+RINFTY
         EXPECTED=EXPECTED*(BOXMOL(I,2)-BOXMOL(I,1))
        END DO
C
C READ PERIODIC
C
        OPEN(90,FILE='PERIODIC',FORM='FORMATTED',STATUS='UNKNOWN')
        REWIND(90)
        DO I=1,3
         READ(90,*)DUMMY
        END DO
        READ(90,*)NPER
        ISOLATED=.FALSE.
        IF (NPER.EQ.0) ISOLATED=.TRUE.
        DO IPER=1,NPER
         READ(90,*)(TVC(J,IPER),J=1,3),FUDGE
         DO J=1,3
          TVC(J,IPER)=FUDGE*TVC(J,IPER)
         END DO
        END DO
        CLOSE(90)
C
C SETUP NLOOP, TVC IF LESS THAN 3 LATTICE VECTORS GIVEN
C
        DO IPER=1,NPER
         NLOOP(IPER)=1
        END DO
        DO IPER=NPER+1,3
         NLOOP(IPER)=0
         DO J=1,3
          TVC(J,IPER)= 0.0D0
         END DO
        END DO
C
C CREATE ATOMS IN NEIGHBOR BOXES
C
        MNUC=NNUC
        DO INUC=1,NNUC
         DO IX= -NLOOP(1),NLOOP(1)
          DO IY= -NLOOP(2),NLOOP(2)
           DO IZ= -NLOOP(3),NLOOP(3)
            IF (IX*IX+IY*IY+IZ*IZ .NE. 0) THEN
             MNUC=MNUC+1
             IF(MNUC .GT. 27*MX_CNT)THEN
              N=(2*NLOOP(1)+1)*(2*NLOOP(2)+1)*(2*NLOOP(3)+1)*NNUC
              PRINT*,'27*MX_CNT IN VMESH MUST BE AT LEAST:',MNUC
              PRINT*,'27*MX_CNT SHOULD BE ABOUT ',N
              STOP
             END IF
             DO J=1,3
              RNUC(J,MNUC)=RNUC(J,INUC)
     &                    +IX*TVC(J,1)+IY*TVC(J,2)+IZ*TVC(J,3)
             END DO
              NPOW(MNUC) = NPOW(INUC)
              ZNUC(MNUC) = ZNUC(INUC)
              NORIG(MNUC)=NORIG(INUC)
            END IF
           END DO
          END DO
         END DO
        END DO
        DO I=1,3
         DO J=1,2
          BOX(J,I)=BOXMOL(I,J)
         END DO
        END DO
C
C DETERMINE CUTOFF ALPHA FOR COULOMB SOLUTION
C
        INQUIRE(FILE='TRANSFORM',EXIST=EXIST)
        IF (.NOT. EXIST) THEN
         RMIN=1.0D30
         DO I=1,MNUC-1
          DO J=I+1,MNUC
           DIST=0.0D0
           DO K=1,3
            DIST=DIST+(RNUC(K,I)-RNUC(K,J))**2
           END DO
           IF (DIST .LT. RMIN) RMIN=DIST
          END DO
         END DO
         PRINT *,'RMIN (N-N) : ',SQRT(RMIN)
         OPEN(30,FILE='TRANSVEC',STATUS='OLD')
         DO I=1,3
          READ(30,*) DUMMY,DUMMY,DUMMY,DUMMY
         END DO
          READ(30,*) ACCUR
         CLOSE(30)
         AMXFT=ACCUR/RMIN
         PRINT *,'AMXFT FROM ACCUR/RMIN**2 : ',AMXFT 
         OPEN(30,FILE='TRANSFORM',STATUS='UNKNOWN')
         REWIND(30)
         NFT=32
         WRITE(30,*) NFT,AMXFT,'  NUMBER OF UNIFORM FT POINTS, AMXFT'
         CLOSE(30)
        END IF
C
C READ BOX
C
        OPEN(55,FILE='PERIODIC',FORM='FORMATTED',STATUS='UNKNOWN')
        REWIND(55)
        DO I=1,3
          READ(55,*) BOX(1,I),BOX(2,I)
        END DO
        CLOSE(55)
        NPER=3
C
        DO I=1,3
         DO J=1,2
          BOXMOL(I,J)=BOX(J,I)
         END DO
        END DO
        EXPECTED=1.0D0
        DO I=1,3
         EXPECTED=EXPECTED*(BOXMOL(I,2)-BOXMOL(I,1))
        END DO
C
C
C ASSIGN EACH ATOM TO THE FIRST BOX. SET UP THE FIRST TWO PLANES IN 
C X/Y/Z DIRECTION TO BE IDENTICAL TO THE BOUNDARY BOX LIMITS.
C INDEXING: PLANE(1/2 FOR LEFT/RIGHT, 1/2/3 FOR X/Y/Z, BOXINDEX)
C CATOM(IBOX) IS TRUE IF BOX IBOX CONTAINS AN ATOM
C 
        DO ICUBE=1,NNUC
         NUMBOX(ICUBE)=1
        END DO  
        DO IC=1,3
         DO J=1,2
          PLANE(J,IC,1)=BOXMOL(IC,J)
         END DO  
        END DO  
        CATOM(1)=.TRUE.
C
C START ADDBOX: CHECK EACH BOX FOR THE NUMBER OF ATOMS CONTAINED AND
C SLICE IT IF MORE THAN ONE ATOM IS IN THE BOX
C
        PRINT *,' '
        PRINT *,'LETS SLICE THE CAKE !'
        MBOX=1
C
C BEGIN OF BOX LOOP
C
  110   CONTINUE
         NBOX=MBOX
         IADD=0
         DO 260 IBOX=1,MBOX
C
C GET NUMBER OF ATOMS THAT ARE IN BOX IBOX 
C
          NATOMS=0
          DO ICUBE=1,NNUC
           IF (NUMBOX(ICUBE).EQ.IBOX) NATOMS=NATOMS+1
          END DO
C
C SLICE BOX IBOX IF IT CONTAINS MORE THAN ONE ATOM
C
          IF(CATOM(IBOX).AND.(NATOMS.GT.1))THEN
           IADD=IADD+1
C
C FIND BEST PLACE TO SLICE BOX IN EITHER X,Y AND Z DIRECTIONS.
C FOR EACH DIRECTION X/Y/Z WRITE COORDINATES OF BOX ATOMS TO XSEP.
C
           NDEG=0
           DMAX=0.0D0
           DO 150 IC=1,3
            NCUBE=0
            DO 120 ICUBE=1,NNUC
             IF(NUMBOX(ICUBE).EQ.IBOX)THEN
              NCUBE=NCUBE+1
              XSEP(NCUBE)=CUBE(IC,ICUBE)
             END IF
  120       CONTINUE
C
C SORT XSEP SMALL -> BIG
C
            DO 130 ICUBE=1,NCUBE
             DO JCUBE=ICUBE+1,NCUBE
              IF(XSEP(JCUBE).LT.XSEP(ICUBE))THEN
               SS=XSEP(JCUBE)
               XSEP(JCUBE)=XSEP(ICUBE)
               XSEP(ICUBE)=SS
              END IF
             END DO   
  130       CONTINUE
C
C SEEK FOR THE MAXIMUM DISTANCE OF ATOMS THAT ARE NEIGHBORS WITH RESPECT
C TO THEIR X/Y/Z COORDINATES (THAT'S WHY WE DID THE SORTING). -> DMAX
C NDEG IS THE DEGENERACY OF DMAX (NUMBER OF DIFFERENT POSSIBILITIES TO
C SLICE THE BOX WITH THE SAME DMAX). XSLICE IS THE COORDINATE FOR THE
C CUT, ISLICE IS 1/2/3 IF THE CUT IS A X/Y/Z PLANE, RESPECTIVELY
C
            DO 140 ICUBE=1,NCUBE-1
             DIST=XSEP(ICUBE+1)-XSEP(ICUBE)
             IF (DIST.GT.(DMAX+TOLER))THEN
              DMAX=XSEP(ICUBE+1)-XSEP(ICUBE)
              NDEG=1
              XSLICE(NDEG)=0.5D0*(XSEP(ICUBE+1)+XSEP(ICUBE))
              ISLICE(NDEG)=IC
             ELSE IF(DIST.GE.(DMAX-TOLER))THEN
              NDEG=NDEG+1
              XSLICE(NDEG)=0.5D0*(XSEP(ICUBE+1)+XSEP(ICUBE))
              ISLICE(NDEG)=IC
             END IF
  140       CONTINUE
  150      CONTINUE

C
C FOR EACH DIRECTION X/Y/Z, PUT OLD BOX BOUNDARIES AND POSSIBLE NEW
C BOX BOUNDARIES INTO XSEP. NXPT(IC) STORES THE NUMBER OF OLD AND 
C POSSIBLE NEW PLANES IN DIRECTION IC.
C
           DO 180 IC=1,3
            XSEP(1)=PLANE(1,IC,IBOX)
            XSEP(2)=PLANE(2,IC,IBOX)
            NXPT(IC)=2
            DO 160 IDEG=1,NDEG
             IF(ISLICE(IDEG).EQ.IC)THEN
              NXPT(IC)=NXPT(IC)+1
              XSEP(NXPT(IC))=XSLICE(IDEG)
             END IF
  160       CONTINUE
C
C SORT COORDINATES OF SLICE PLANES AND COPY THEM ALL TO BX
C
            DO 170 IX=1,NXPT(IC)
             DO JX=IX+1,NXPT(IC)
              IF(XSEP(JX).LT.XSEP(IX))THEN
               ATMP=XSEP(IX)
               XSEP(IX)=XSEP(JX)
               XSEP(JX)=ATMP
              END IF
             END DO
             BCUT(IC,IX)=XSEP(IX)
  170       CONTINUE
  180      CONTINUE
C
C ADD NEW BOXES. ALL DEGENARATE BOXES MUST BE ADDED TO PREVENT
C THE SYMMETRY FROM GETTING SCREWED UP. THE NEW PLANES ARE ADDED 
C FOR X/Y/Z WHILE THE BOX INDEX IS UPDATED
C NNBOX IS SET UP SO THAT THE OLD BOX SLOT IS FILLED WITH A NEW BOX
C
           NNEW=NBOX+NXPT(1)*NXPT(2)*NXPT(3)
           IF(NNEW.GT.MXCUBE)THEN
            PRINT *,'VMESH: MXCUBE MUST BE AT LEST: ',NNEW
            STOP
           END IF
           VTOT=
     &      (PLANE(2,1,IBOX)-PLANE(1,1,IBOX))*
     &      (PLANE(2,2,IBOX)-PLANE(1,2,IBOX))*
     &      (PLANE(2,3,IBOX)-PLANE(1,3,IBOX))
           NBOX=NBOX-1
           DO 230 IB=1,NXPT(1)-1
            DO 220 JB=1,NXPT(2)-1
             DO 210 KB=1,NXPT(3)-1
              NBOX=NBOX+1
              NNBOX=NBOX
              IF(IB*JB*KB.EQ.1)NNBOX=IBOX
              PLANE(1,1,NNBOX)=BCUT(1,IB  )
              PLANE(2,1,NNBOX)=BCUT(1,IB+1)
              PLANE(1,2,NNBOX)=BCUT(2,JB  )
              PLANE(2,2,NNBOX)=BCUT(2,JB+1)
              PLANE(1,3,NNBOX)=BCUT(3,KB  )
              PLANE(2,3,NNBOX)=BCUT(3,KB+1)
              VTOT=VTOT-
     &         (PLANE(2,1,NNBOX)-PLANE(1,1,NNBOX))*
     &         (PLANE(2,2,NNBOX)-PLANE(1,2,NNBOX))*
     &         (PLANE(2,3,NNBOX)-PLANE(1,3,NNBOX))
  210        CONTINUE
  220       CONTINUE
  230      CONTINUE
C
C REASSIGN ATOMS TO THE APPROPRIATE BOX AND UPDATE CATOM
C
           DO JBOX=1,NBOX
            CATOM(JBOX)=.FALSE.
           END DO  
           DO 250 JBOX=1,NBOX
            DO 240 ICUBE=1,NNUC
             INBOX=.TRUE.
             DO IC=1,3
              IF(CUBE(IC,ICUBE).LT.PLANE(1,IC,JBOX))INBOX=.FALSE.
              IF(CUBE(IC,ICUBE).GT.PLANE(2,IC,JBOX))INBOX=.FALSE.
             END DO  
             IF(INBOX)THEN
              NUMBOX(ICUBE)=JBOX
              CATOM(JBOX)=.TRUE.
             END IF
  240       CONTINUE
  250      CONTINUE
          END IF
  260    CONTINUE
C
C CALCULATE THE TOTAL VOLUME OF OUR NEW BOX COLLECTION. UPDATE 
C MBOX AND GO BACK TO LABEL 10 IF THERE IS STILL SOMETHING TO DO
C
         VOLUM=0.0D0
         DO IBOX=1,NBOX
          VOLUM=VOLUM+
     &     (PLANE(2,1,IBOX)-PLANE(1,1,IBOX))*
     &     (PLANE(2,2,IBOX)-PLANE(1,2,IBOX))*
     &     (PLANE(2,3,IBOX)-PLANE(1,3,IBOX))
         END DO
         MBOX=NBOX
         PRINT 8030,'NBOX, VOLUME, EXPECTED:',NBOX,VOLUM,EXPECTED
         IF(IADD.NE.0) GOTO 110
        CONTINUE
C
C END OF BOX LOOP
C
C SETUP OF SIDE FOR ALL BOXES CONTAINING ATOMS. SIDE IS THE DISTANCE 
C BETWEEN AN ATOM AND THE CORRESPONDING BOUNDARY BOX. 
C
        DO 270 ICUBE=1,NNUC
         DO IBOX=1,NBOX
          IF(NUMBOX(ICUBE).EQ.IBOX)THEN
           DO IC=1,3
            DO J=1,2
             SIDE(J,IC,ICUBE)=PLANE(J,IC,IBOX)-CUBE(IC,ICUBE)
            END DO  
           END DO  
          END IF
         END DO  
  270   CONTINUE
C
C FILL ARRAYS CUBE AND SIDE WITH BOXES THAT DO NOT CONTAIN ATOMS
C
        NCUBE=NNUC
        DO 280 IBOX=1,NBOX
         IF(.NOT.CATOM(IBOX))THEN
          NCUBE=NCUBE+1
          DO IC=1,3
           CUBE(IC,NCUBE)=0.5D0*(PLANE(2,IC,IBOX)+PLANE(1,IC,IBOX)) 
          END DO  
          DO IC=1,3
           DO J=1,2
            SIDE(J,IC,NCUBE)=PLANE(J,IC,IBOX)-CUBE(IC,NCUBE)
           END DO  
          END DO  
         END IF
  280   CONTINUE
C
C REPLACE EACH PARALLELPIPED BY A CUBE SURROUNDING EACH ATOM PLUS OTHER
C PARALLELPIPEDS SURROUNDING VOIDS. 
C
        DO 340 ICUBE=1,NNUC
C
C CALCULATE VOLUME OF BOX. GET THE SMALLEST DISTANCE FROM THE CENTER
C TO THE BOX BOUNDARY. 
C  
         RMIN=1.0D30
         VTOT=1.0D0
         DO 290 IC=1,3
          VTOT=VTOT+(SIDE(2,IC,ICUBE)-SIDE(1,IC,ICUBE))
          DO J=1,2
           ATMP=ABS(SIDE(J,IC,ICUBE))
           IF(ATMP.LT.RMIN)RMIN=ATMP
          END DO  
  290    CONTINUE
C
C SUBTRACT VOLUME OF ATOMIC CUBE FROM THE TOTAL BOX VOLUME.
C PUT NEW BOX BOUNDARIES INTO BX. UPDATE BOUNDARIES FOR ATOMIC CUBE.
C
         VTOT=VTOT-(2*RMIN)**3
         DO 300 IC=1,3
          BCUT(IC,1)=  SIDE(1,IC,ICUBE)
          BCUT(IC,2)= -RMIN
          BCUT(IC,3)=  RMIN
          BCUT(IC,4)=  SIDE(2,IC,ICUBE)
          SIDE(1,IC,ICUBE)= -RMIN
          SIDE(2,IC,ICUBE)=  RMIN
  300    CONTINUE
C
C WITH THE HELP OF BX, WE HAVE TO UPDATE THE ARRAYS SIDE AND CUBE AS IF 
C WE WERE SLICING THE OLD BOX INTO 3 PIECES FOR EACH DIRECTION. WHILE
C DOING THIS, UPDATE NCUBE EXCEPT FOR THE CASE OF THE ATOMIC CUBE.
C IGNORE BOXES WITH ZERO VOLUME
C
         DO 330 IB=1,3
          DO 320 JB=1,3
           DO 310 KB=1,3
            IF(IB*JB*KB.NE.8)THEN
             NCUBE=NCUBE+1
             SIDE(1,1,NCUBE)=BCUT(1,IB  )
             SIDE(2,1,NCUBE)=BCUT(1,IB+1)
             SIDE(1,2,NCUBE)=BCUT(2,JB  )
             SIDE(2,2,NCUBE)=BCUT(2,JB+1)
             SIDE(1,3,NCUBE)=BCUT(3,KB  )
             SIDE(2,3,NCUBE)=BCUT(3,KB+1)
             VOLUM=1.0D0
             DO IC=1,3
              AVG=0.5D0*(SIDE(2,IC,NCUBE)+SIDE(1,IC,NCUBE))
              DIF=0.5D0*(SIDE(2,IC,NCUBE)-SIDE(1,IC,NCUBE))
              VOLUM=VOLUM*DIF*2
              CUBE(IC,NCUBE)=CUBE(IC,ICUBE)+AVG
              SIDE(2,IC,NCUBE)=  DIF
              SIDE(1,IC,NCUBE)= -DIF
             END DO
             VTOT=VTOT-VOLUM
C             PRINT*,'VOL : ', VOLUM
             IF(VOLUM. EQ. 0.0D0)NCUBE=NCUBE-1
            END IF
  310      CONTINUE
  320     CONTINUE
  330    CONTINUE
  340   CONTINUE
C
C CHECK TOTAL VOLUME
C
        VOLUM=0.0D0
        DO ICUBE=1,NCUBE
         VOLUM=VOLUM
     &        +8*SIDE(2,1,ICUBE)*SIDE(2,2,ICUBE)*SIDE(2,3,ICUBE)
        END DO
        AVOL=VOLUM
        PRINT 8040,'TOTAL VOLUME:',AVOL,'EXPECTED:',EXPECTED
        PRINT 8040,'TOTAL VOLUME:',VOLUM,'EXPECTED:',EXPECTED
C
C LETS GET RID OF THOSE REALLY TINY CUBES FIRST
C
        VOLUM=0.0D0
        KCUBE=0
        DO 370 ICUBE=1,NCUBE
         VCUB=8*SIDE(2,1,ICUBE)*SIDE(2,2,ICUBE)*SIDE(2,3,ICUBE)
         IF(VCUB.GT.VOLTL)THEN
          KCUBE=KCUBE+1
          DO I=1,3
           CUBE(I,KCUBE)=CUBE(I,ICUBE)
           SIDE(1,I,KCUBE)=SIDE(1,I,ICUBE)
           SIDE(2,I,KCUBE)=SIDE(2,I,ICUBE)
          END DO
          RSQVOL(1,KCUBE)=
     &     CUBE(1,KCUBE)**2+CUBE(2,KCUBE)**2+CUBE(3,KCUBE)**2
          RSQVOL(2,KCUBE)=VCUB
          VOLUM=VOLUM+VCUB
         END IF
  370   CONTINUE
        NCUBE=KCUBE
C
C PRINT PARAMETERS OF CURRENT BOX SET
C
        PRINT *,' '
        PRINT *,'CURRENT BOX PARAMETERS:'
        DO ICUBE=1,NCUBE
         PRINT 8050,'BOX',ICUBE
         PRINT 8020,'CENTER',(CUBE(I,ICUBE), I=1,3)
         PRINT 8020,'LEFT  ',(SIDE(1,I,ICUBE), I=1,3)
         PRINT 8020,'RIGHT ',(SIDE(2,I,ICUBE), I=1,3)
        END DO  
        PRINT 8040,'TOTAL VOLUME:',VOLUM,'EXPECTED:',EXPECTED
C
C NOW PURGE OUT THE REDUNDANCIES AND KEEP TRACK OF MULTIPLICITIES FOR 
C EACH IDENTITY CUBE. ASSIGN MULTIPLICITIES TO NUMBOX.
C
        PRINT *,' '
        PRINT *,'REMOVING BOXES THAT ARE EQUIVALENT DUE TO SYMMETRY'
        DO ICUBE=1,NCUBE
         NUMBOX(ICUBE)=0
        END DO
        DO 400 ICUBE=1,NCUBE
         IF(RSQVOL(2,ICUBE) .GE. 0.0D0)THEN
        IF(NPOW(1).NE.0)STOP            
          NUMBOX(ICUBE)=MX_GRP
          CALL GASITES(3,CUBE(1,ICUBE),NUMBOX(ICUBE),RIDENT)
          IF(NUMBOX(ICUBE).GT.MX_GRP)STOP'OOPS'
        IF(NPOW(1).NE.0)THEN
          NUMBOX(ICUBE)=MX_GRP
          CALL GASITES(3,CUBE(1,ICUBE),NUMBOX(ICUBE),RIDENT)
        STOP            
        END IF
          IFOUND=1
          DO 390 JCUBE=ICUBE+1,NCUBE
           IF((ABS(RSQVOL(1,ICUBE)-RSQVOL(1,JCUBE)).LE.TOLER) .AND.
     &        (ABS(RSQVOL(2,ICUBE)-RSQVOL(2,JCUBE)).LE.TOLER)) THEN
C
C CHECK IF THIS CUBE IS EQUAL TO ONE OF THOSE GENERATED
C
            DO 380 KCUBE=1,NUMBOX(ICUBE)
             ERROR=ABS(CUBE(1,JCUBE)-RIDENT(1,KCUBE))+
     &             ABS(CUBE(2,JCUBE)-RIDENT(2,KCUBE))+
     &             ABS(CUBE(3,JCUBE)-RIDENT(3,KCUBE))
             IF(ERROR.LE.TOLER)THEN
              IFOUND=IFOUND+1
              RSQVOL(2,JCUBE)= -1.0D30
             END IF
  380       CONTINUE
           END IF
  390     CONTINUE
          PRINT *,'ANTICIPATED NUMBER OF CUBES:'
     &            ,NUMBOX(ICUBE),' FOUND: ',IFOUND
C
C IF WE DID NOT FIND ALL CUBES, PRINT OUT THE MESS AND STOP
C
          IF(IFOUND.NE.NUMBOX(ICUBE))THEN
           PRINT *,'ERROR IN VMESH'
           PRINT *,'IFOUND= ',IFOUND,' EXPECTED ',NUMBOX(ICUBE)
           PRINT *,'ICUBE=  ',ICUBE,' NCUBE= ',NCUBE
           PRINT *,'VMESH: IFOUND AND NUMBOX ARE NOT EQUAL'
           STOP
          END IF
         END IF
  400   CONTINUE
C
C MOVE ZNUC INFORMATION TO ZTEST
C
        DO ICUBE=1,NNUC
         ZTEST(ICUBE)=ZNUC(ICUBE)
        END DO
C
C ERASE ALL BOXES THAT ARE EQIVALENT DUE TO SYMMETRY
C
        KCUBE=0
        NATOMS=0
        VOLUM=0.0D0
        DO 410 ICUBE=1,NCUBE
         IF(RSQVOL(2,ICUBE) .GT. 0.0D0)THEN
          KCUBE=KCUBE+1
          NUMBOX(KCUBE)=NUMBOX(ICUBE)
          IF(ICUBE.LE.NNUC)THEN
           NATOMS=NATOMS+1
           NORIG(KCUBE)=NORIG(ICUBE)
           ZNUC(KCUBE)=ZNUC(ICUBE)
          END IF
          DO J=1,3
           CUBE(J,KCUBE)=CUBE(J,ICUBE)
           SIDE(1,J,KCUBE)=SIDE(1,J,ICUBE)
           SIDE(2,J,KCUBE)=SIDE(2,J,ICUBE)
          END DO
          VCUB=8*SIDE(2,1,KCUBE)*SIDE(2,2,KCUBE)*SIDE(2,3,KCUBE)
          VOLUM=VOLUM+VCUB*NUMBOX(KCUBE)
         END IF
  410   CONTINUE
        NCUBE=KCUBE
C
C PRINT SURVIVING BOXES
C
        PRINT *,' '
        PRINT *,'INEQUIVALENT BOXES:'
        DO ICUBE=1,NCUBE
         PRINT 8050,'BOX',ICUBE,'MULTIPLICITY:',NUMBOX(ICUBE)
         PRINT 8020,'CENTER',(CUBE(I,ICUBE), I=1,3)
         PRINT 8020,'LEFT  ',(SIDE(1,I,ICUBE), I=1,3)
         PRINT 8020,'RIGHT ',(SIDE(2,I,ICUBE), I=1,3)
        END DO  
        PRINT 8040,'TOTAL VOLUME:',VOLUM,'EXPECTED:',EXPECTED
C
C TRY TO SLICE INTERSTITIAL BOXES WHICH TRANSFORM INTO THEMSELVES.
C DO ONLY TWO CYCLES TO AVOID ENDLESS LOOPS.
C WE NEED TO MAKE SURE CUBE IS LARGE ENOUGH.
C
        PRINT *,' '
        PRINT *,'CHECKING FOR BOXES THAT TRANSFORM INTO THEMSELVES'
        NTOTAL=NCUBE
  420   CONTINUE
         OK=.TRUE.
         NCUBE=NTOTAL
         DO 480 ICUBE=NUNIQUE+1,NCUBE
          NCREAT=0
          IF((NTOTAL+8).GT.MXCUBE)THEN
           PRINT *,'VMESH: MXCUBE MUST BE AT LEAST: ',NTOTAL+8
           STOP
          END IF
C
C FIND GROUP OPERATIONS THAT LEAVE CENTER OF CUBE UNCHANGED
C
          NTRAF=0
          DO 430 IGRP=1,NGPERM
           DIF=0.0D0
           DO J=1,3
            RTMP=0.0D0
            DO K=1,3
             RTMP=RTMP+RMAT(K,J,IGRP)*CUBE(K,ICUBE)
            END DO
            DIF=DIF+ABS(RTMP-CUBE(J,ICUBE))
           END DO
           IF(DIF.LT.TOLER)THEN
            NTRAF=NTRAF+1
            NSYMOP(NTRAF)=IGRP
           END IF
  430     CONTINUE
C
C IF WE FIND MORE THAN ONE SYMMETRY OPERATION, TRY DIFFERENT
C POSSIBILITIES OF SLICING. STORE BOX SIZE IN WX.
C INITIALIZE NXPT
C
          IF(NTRAF.GE.2)THEN
           GAIN=1.0D0
           DO 470 ITRY=1,7
            IM1=MOD((ITRY-1),3)+1
            II1=MIN(((ITRY+2)/3),2)
            II2=MOD(II1,2)+1
            IF(ITRY.EQ.7)II2=II1
            DO I=1,3
             NXPT(I)=II1
            END DO
            NXPT(IM1)=II2
C
C SLICE INTO AT MOST EIGHT BOXES
C
            DO IC=1,3
             IF(NXPT(IC).EQ.1)THEN
              RX(IC)=   SIDE(2,IC,ICUBE)
              BOX(1,IC)=CUBE(IC,ICUBE)
             ELSE
              RX(IC)=   0.5D0*SIDE(2,IC,ICUBE)
              BOX(1,IC)=CUBE(IC,ICUBE)-0.5D0*SIDE(2,IC,ICUBE)
              BOX(2,IC)=CUBE(IC,ICUBE)+0.5D0*SIDE(2,IC,ICUBE)
             END IF
            END DO
            NADD=0
            DO IX=1,NXPT(1)
             DO IY=1,NXPT(2)
              DO IZ=1,NXPT(3)
               NADD=NADD+1
               BCUT(1,NADD)=BOX(IX,1)
               BCUT(2,NADD)=BOX(IY,2)
               BCUT(3,NADD)=BOX(IZ,3)
              END DO
             END DO 
            END DO  
C
C CHECK WHICH OF THESE BOXES ARE EQUIVALENT TO EACH OTHER
C USE NFBUF AS INDICATOR WHETER THIS BOX HAS ALREADY BEEN FOUND
C
            DO IBX=1,NADD
             NFBUF(IBX)=1
            END DO
            NFOUND=0
            DO 460 IBX=1,NADD
             IF(NFBUF(IBX).NE.0)THEN
              NFOUND=NFOUND+1
              DO 450 JBX=IBX+1,NADD
               IF(NFBUF(JBX).NE.0)THEN
                DO 440 ITRAF=1,NTRAF
                 IGRP=NSYMOP(ITRAF)
                 DIF=0.0D0
                 DO J=1,3
                  RTMP=0.0D0
                  DO K=1,3
                   RTMP=RTMP+RMAT(K,J,IGRP)*BCUT(K,IBX)
                  END DO
                  DIF=DIF+ABS(RTMP-BCUT(J,JBX))
                 END DO
                 IF(DIF.LT.TOLER)NFBUF(JBX)=0
  440           CONTINUE
                IF(NFBUF(JBX).EQ.0)NFBUF(IBX)=NFBUF(IBX)+1
               END IF
  450         CONTINUE
             END IF
  460       CONTINUE
C
C CHECK IF THE RESULT IS WORTH NOTING. IF YES, PUT THE CANDIDATE
C CUBES AT THE END OF ARRAY CUBE
C
            RATIO=NFOUND
            RATIO=NADD/RATIO
            IF((GAIN+TOLER).LT.RATIO)THEN
             GAIN=RATIO
             NCREAT=0
             DO IBX=1,NADD
              IF(NFBUF(IBX).NE.0)THEN
               NCREAT=NCREAT+1
               NUMBOX(NTOTAL+NCREAT)=NFBUF(IBX)*NUMBOX(ICUBE)
               DO I=1,3
                CUBE(I,NTOTAL+NCREAT)=BCUT(I,IBX)
                SIDE(1,I,NTOTAL+NCREAT)= -RX(I)
                SIDE(2,I,NTOTAL+NCREAT)=  RX(I)
               END DO
              END IF
             END DO
            END IF
  470      CONTINUE
          END IF
C
C CHECK IF WE REALLY WANT TO SPLIT THAT PARTICULAR BOX
C FIND DISTANCE TO CLOSEST ATOM
C
          IF(NCREAT.NE.0)THEN
           DCLOS=1.0D30
           DO INUC=1,NNUC
            DIST=0.0D0
            DO I=1,3
             XXX=RNUC(I,INUC)
             XLEFT= CUBE(I,ICUBE)-SIDE(2,I,ICUBE)
             XRIGHT=CUBE(I,ICUBE)+SIDE(2,I,ICUBE)
             IF(RNUC(I,INUC).LT.XLEFT) XXX=XLEFT
             IF(RNUC(I,INUC).GT.XRIGHT)XXX=XRIGHT
             DIST=DIST+(RNUC(I,INUC)-XXX)**2
            END DO
            DCLOS=MIN(DCLOS,DIST)
           END DO
           DALLOW=CUTFAC*DIST
C
C CHECK IF THE BOX IS LARGER THAN DALLOW IN ONE OR MORE 
C DIMENSIONS. IF YES, CHECK IF THE PROPOSED CUT WILL ACTUALLY
C CHANGE THE CORRESPONDING COMPONENT OF THE BOX SIZE.
C
           FIXIT=.FALSE.           
           DO IC=1,3
            XXX=SIDE(2,IC,ICUBE)
            IF(XXX.GT.DALLOW)THEN
             IF(ABS(XXX-SIDE(2,IC,NTOTAL+1)).GT.TOLER)FIXIT=.TRUE.
            END IF
           END DO
           IF(NCREAT.EQ.1)FIXIT=.TRUE.
C
C MOVE NEW BOXES TO THE RIGHT LOCATION
C
           IF(FIXIT)THEN
            OK=.FALSE.
            PRINT *,'CUTTING BOX ',ICUBE,', GAIN= ',GAIN
            NUMBOX(ICUBE)=NUMBOX(NTOTAL+NCREAT)
            DO I=1,3
             CUBE(I,ICUBE)=CUBE(I,NTOTAL+NCREAT)
             SIDE(1,I,ICUBE)=SIDE(1,I,NTOTAL+NCREAT)
             SIDE(2,I,ICUBE)=SIDE(2,I,NTOTAL+NCREAT)
            END DO
            NTOTAL=NTOTAL+NCREAT-1
           END IF
          END IF
  480    CONTINUE
         IF(.NOT.OK)GOTO 420
        CONTINUE
        NCUBE=NTOTAL
C
C ZERO NORIG FOR INTERSTITIALS (ONLY FOR PRINTING PURPOSES)
C
        DO ICUBE=NUNIQUE+1,NCUBE
         NORIG(ICUBE)=0
        END DO
C           
C PRINT FINAL BOX SET AND CHECK THE VOLUME AGAIN
C
        PRINT *,' '
        PRINT *,'FINAL BOX SET:'
        VOLUM=0.0D0
        DO ICUBE=1,NCUBE
         PRINT 8050,'BOX',ICUBE,'MULTIPLICITY:',NUMBOX(ICUBE),
     &           'ID MEMBER:',NORIG(ICUBE)
         PRINT 8020,'CENTER',(CUBE(I,ICUBE), I=1,3)
         PRINT 8020,'LEFT  ',(SIDE(1,I,ICUBE), I=1,3)
         PRINT 8020,'RIGHT ',(SIDE(2,I,ICUBE), I=1,3)
         VBOX=8*SIDE(2,1,ICUBE)*SIDE(2,2,ICUBE)*SIDE(2,3,ICUBE)
         VOLUM=VOLUM+NUMBOX(ICUBE)*VBOX
        END DO  
        PRINT 8040,'TOTAL VOLUME:',VOLUM,'EXPECTED:',EXPECTED
C
C START FILLING CUBES UP WITH MESH POINTS. FIRST THE ATOMIC CUBES.
C WE NEED:  * ONE SPHERE MESH FROM 0 TO RSPH PER IDENTITY MEMBER
C           * ONE SPHERE MESH FROM RSPH TO RBOX PER UNIQUE ATOM
C           * EXCLUDED REGION MESH PER UNIQUE ATOM (BOX SIZE RBOX)
C
C SET NGRP BACK TO NGFULL.
C LOOP OVER ALL IDENTITY MEMBERS. GET MINIMUM SPHERE RADIUS RSPH.
C
        PRINT *,' '
        PRINT *,'FILLING CUBES THAT CONTAIN ATOMS'
        NGRP=NGFULL
        NPTS=0
        DO 550 IIDENT=1,NIDENT
         NDEG=0
         RSPH=1.0D30
         VINNER=0.0D0
         DO IATOM=1,NUNIQUE
          IF(NORIG(IATOM).EQ.IIDENT)THEN
           NDEG=NDEG+NUMBOX(IATOM)
           RSPH=MIN(RSPH,SIDE(2,1,IATOM))
          END IF
         END DO
         IF(NDEG.EQ.0)THEN
          PRINT *,'VMESH: IDENTITY MEMBER: ',IIDENT
          PRINT *,'IS NOT ASSOCIATED WITH ANY UNIQUE ATOMS'
          STOP
         END IF
         ERRSPH=ERRAT
         IF(LSYWT)ERRSPH=ERRAT/NDEG 
         PRINT *,' '
         PRINT *,'IDENTITY MEMBER ',IIDENT,
     &           ' MULTIPLICITY: ',NDEG
         IFOUND=0
C
C LOOP OVER ALL UNIQUE ATOMS
C
         DO 540 IATOM=1,NUNIQUE
          IF(NORIG(IATOM).EQ.IIDENT)THEN
           PRINT *,' '
           PRINT *,'UNIQUE ATOM     ',IATOM, 
     &             ' MULTIPLICITY: ',NUMBOX(IATOM)
           IFOUND=IFOUND+1
C
C GET ATOM TYPE
C
           ITYP=NTYP
           DO JTYP=NTYP-1, 1, -1
            IF(ZNUC(IATOM).LE.ZZON(JTYP))ITYP=JTYP
           END DO
C
C SETUP INPUT FOR FLACUB AND CALL FLACUB
C RADIAL POINTS HAVE TO BE IN RBUF(1,I)
C
           RBOX=SIDE(2,1,IATOM)
           ERRBOX=ERRAT
           IF(LSYWT)ERRBOX=ERRAT/NUMBOX(IATOM)
           ALMAX=FACZ2*ZNUC(IATOM)**2
           NPOLY=NPATS(ITYP) 
           PRINT 8040,'ZNUC:',ZNUC(IATOM),'RADIUS:',RBOX
           PRINT *,'CALLING FLACUB'
           CALL FLACUB(MXCPTS,NR1,NR2,NCTOT,RBUF,WBUF,NPHI(ITYP),
     &                 NTHET(ITYP),RSPH,RBOX,ERRSPH,ERRBOX,A1AT,
     &                 ALMAX,AFUDAT,NPOLY)
           NRAD=NR1+NR2
           PRINT *,'AFTER FLACUB: NPTS= ',NCTOT,
     &             ' NR1= ',NR1,' NR2= ',NR2
           IF(NRAD.GT.MXRAD)THEN
            PRINT *,'VMESH: MXRAD MUST BE AT LEAST: ',NRAD
            STOP
           END IF
C
C TEST VOLUME AND RENORMALIZE RADIAL WEIGHTS
C
           VOLUM=0.0D0
           ATMP=1.0D0/(4*PI)
           DO IPTS=1,NRAD
            VOLUM=VOLUM+WBUF(IPTS)
            WBUF(IPTS)=WBUF(IPTS)*ATMP
           END DO
           DO IPTS=NRAD+1,NCTOT
            VOLUM=VOLUM+48*WBUF(IPTS)
           END DO
           EXACT=8*RBOX**3
           PRINT 8040,'CUBE VOLUME:',VOLUM,'EXACT:',EXACT
C
C ADD RADIAL POINTS. IF (IFOUND.EQ.1), WE HAVE TO ADD THE MESH FOR 
C THE INNER SPHERE FROM 0 TO RSPH. NOTE THAT IN THIS CASE NGRP=NFULL
C IS NECESSARY WHILE FOR THE OTHER RADIAL MESH NGRP=NGPERM IS CORRECT.
C 
           PRINT *,' '
           PRINT *,'ADDING RADIAL + ANGULAR POINTS'
           MSTART=2
           IF(IFOUND.EQ.1)MSTART=1
           DO 510 IMESH=MSTART,2
            IF(IMESH.EQ.1)THEN
             NGRP=NGFULL
             NSITES=NDEG 
             ISTART=1
             IEND=NR1
            ELSE
             NGRP=NGPERM
             NSITES=NUMBOX(IATOM) 
             ISTART=NR1+1
             IEND=NR1+NR2
            END IF
            NSAVP=NPTS
C
C FOR EACH ZONE, FIND ASSOCIATED RADIAL POINTS
C
            DO 500 IRZ=1,NRZONE
             IR=0
             DO JR=ISTART,IEND
              IF(RBUF(1,JR).LT.RZON(IRZ))THEN
               IR=IR+1
               RX(JR-ISTART+1)=RBUF(1,JR)
               WX(JR-ISTART+1)=WBUF(JR)
              ELSE
               GOTO 490
              END IF
             END DO
  490        CONTINUE
             ISTART=ISTART+IR
             IF(IR.EQ.0)GOTO 500
C
C GET ANGULAR MESH AND CALL ADDPTS
C
             CALL ANGMSH(MXANG,LMXA(IRZ,ITYP),IANP,ANGLE,DOMEGA)
             PRINT *,'IATOM: ',IATOM,' RAD/ANG MESH ',IMESH,IRZ
             PRINT 8020,'CENTER:',(CUBE(K,IATOM),K=1,3)
             CALL ADDPTS(NSITES,CUBE(1,IATOM),RX,WX,ANGLE,DOMEGA,
     &                   IR,IANP)
  500       CONTINUE
C
C GET NUMERICAL VALUE OF SPHERE VOLUME
C
            PRINT *,'SPHERE FILLED, NPTS= ',NPTS
            IF(NPTS.GT.MAX_PTS)THEN
             PRINT *,'VMESH: MAX_PTS MUST BE AT LEAST: ',NPTS
             STOP
            END IF
            VOLSPH=0.0D0
            DO IPTS=NSAVP+1,NPTS
             VOLSPH=VOLSPH+DV(1,IPTS)
            END DO
            ATMP=NSITES
            VOLSPH=VOLSPH/ATMP
            IF(IMESH.EQ.1)VINNER=VOLSPH
  510      CONTINUE
           CORSPH=(4*PI/3.0D0)*RBOX**3
           PRINT 8040,'VSPHERE:',VOLSPH+VINNER,'CORRECT:',CORSPH
C
C THE SPHERES ARE DONE. 
C NOW THE PART OUTSIDE THE SPHERE BUT INSIDE THE CUBE
C GET ALL 48 POINTS
C
           PRINT *,' '
           PRINT *,'ADDING POINTS FOR EXCLUDED CUBIC REGION'
           NSAVP=NPTS
           DO 530 IPTS=NRAD+1,NCTOT
            RX(1)=1.0D0
            WX(1)=WBUF(IPTS)
            XXX=RBUF(1,IPTS)
            YYY=RBUF(2,IPTS)
            ZZZ=RBUF(3,IPTS)
            IANP=0
            DO 520 IX=1,2
             XXX= -XXX
             DO IY=1,2
              YYY= -YYY 
              DO IZ=1,2
               ZZZ= -ZZZ
               DO ISW=1,2
                ATMP=XXX 
                XXX= YYY
                YYY= ATMP
                DO IPM=1,3
                 IANP=IANP+1
                 ATMP=ZZZ
                 ZZZ= YYY
                 YYY= XXX
                 XXX= ATMP
                 ANGLE(1,IANP)=XXX 
                 ANGLE(2,IANP)=YYY
                 ANGLE(3,IANP)=ZZZ
                 DOMEGA(IANP)=1.0D0
                END DO
               END DO
              END DO
             END DO
  520       CONTINUE
            CALL ADDPTS(NSITES,CUBE(1,IATOM),RX,WX,ANGLE,DOMEGA,1,48)
  530      CONTINUE
C
C GET NUMERICAL VALUE FOR EXCLUDED VOLUME
C
           IF(NPTS.GT.MAX_PTS)THEN
            PRINT *,'VMESH: MAX_PTS MUST BE AT LEAST: ',NPTS
            STOP
           END IF
           VEXCL=0.0D0
           DO IPTS=NSAVP+1,NPTS
            VEXCL=VEXCL+DV(1,IPTS)
           END DO
           ATMP=NSITES
           VEXCL=VEXCL/ATMP
           COREX=(8-(4*PI/3.0D0))*RBOX**3
           PRINT *,'AFTER EXCLUDED CUBIC REGION, NPTS= ',NPTS
           PRINT 8040,'VEXCL:',VEXCL,'CORRECT:',COREX
          END IF
  540    CONTINUE
  550   CONTINUE
C
C ADD THE INTERSTITIAL POINTS
C
        PRINT *,' '
        PRINT *,'STARTING INTERSTITIAL POINTS'
C
C LOOP OVER ALL ORIGINAL CUBES. SET BACK NGRP FIRST.
C
        NGRP=NGFULL
        DO 650 IATOM=NUNIQUE+1,NCUBE
         LREPAIR= .FALSE.
C
C SETUP INPUT FOR IS1DIM
C
         ERRBOX=ERRIS
         IF(LSYWT)ERRBOX=ERRIS/NUMBOX(IATOM)
         NTOTAL=NCUBE
         JATOM=IATOM-1
C
C LOOP OVER ALL CUBES BELONGING TO THE ORIGINAL CUBE IATOM
C
  570    CONTINUE
          JATOM=JATOM+1
          VINT=SIDE(2,1,JATOM)*SIDE(2,2,JATOM)*SIDE(2,3,JATOM)*8
          PRINT *,' '
          PRINT 8070,'CUBE: ',JATOM,' VOLUME= ',VINT,
     &            ' MULTIPLICITY: ',NUMBOX(JATOM)
          PRINT*,(CUBE(IC,JATOM),IC=1,3)
          DO IC=1,3
           BOX(1,IC)= -SIDE(2,IC,JATOM)+CUBE(IC,JATOM)
           BOX(2,IC)=  SIDE(2,IC,JATOM)+CUBE(IC,JATOM)
          END DO
C
C TRY TO FIND ADEQUATE ONE-DIMENSIONAL MESHES
C
          CALL IS1DIM(A1IS,AFUDIS,ERRBOX,NPOW,BOX,MNUC,RNUC,
     &                1,RX,WX,NX,OKXYZ(1),MX1D)
          CALL IS1DIM(A1IS,AFUDIS,ERRBOX,NPOW,BOX,MNUC,RNUC,
     &                2,RY,WY,NY,OKXYZ(2),MX1D)
          CALL IS1DIM(A1IS,AFUDIS,ERRBOX,NPOW,BOX,MNUC,RNUC,
     &                3,RZ,WZ,NZ,OKXYZ(3),MX1D)
          OK=OKXYZ(1).AND.OKXYZ(2).AND.OKXYZ(3)
C
C PARTITION CUBE INTO AT MOST EIGHT NEW CUBES
C
          IF(.NOT.OK)THEN
           DO 580 ICORD=1,3
            IF(OKXYZ(ICORD))THEN
             NXPT(ICORD)=1
             BOX(1,ICORD)=CUBE(ICORD,JATOM)
             RX(ICORD)=SIDE(2,ICORD,JATOM)
            ELSE
             NXPT(ICORD)=2
             RX(ICORD)=0.5D0*SIDE(2,ICORD,JATOM)
             BOX(1,ICORD)=CUBE(ICORD,JATOM)-0.5D0*SIDE(2,ICORD,JATOM)
             BOX(2,ICORD)=CUBE(ICORD,JATOM)+0.5D0*SIDE(2,ICORD,JATOM)
            END IF
  580      CONTINUE
           NNEW=NTOTAL+NXPT(1)*NXPT(2)*NXPT(3)
           IF(NNEW.GT.MXCUBE)THEN
            PRINT *,'VMESH: MXCUBE MUST BE AT LEAST: ',NNEW
            STOP
           END IF
           DO 590 IX=1,NXPT(1)
            DO IY=1,NXPT(2)
             DO IZ=1,NXPT(3)
              NTOTAL=NTOTAL+1
              PRINT *,'NEW CUBE, NTOTAL:',NTOTAL
              CUBE(1,NTOTAL)=BOX(IX,1)
              CUBE(2,NTOTAL)=BOX(IY,2)
              CUBE(3,NTOTAL)=BOX(IZ,3)
              NUMBOX(NTOTAL)=NUMBOX(JATOM)
              DO ICORD=1,3
               SIDE(1,ICORD,NTOTAL)= -RX(ICORD)
               SIDE(2,ICORD,NTOTAL)=  RX(ICORD)
              END DO
             END DO 
            END DO  
  590      CONTINUE
C
C SET JATOM TO THE END OF THE LIST COINTAINING ALL ORIGINAL CUBES
C
           LREPAIR= .TRUE.
           IF(JATOM.LT.NCUBE)JATOM=NCUBE
C
C DEAL WITH A SUCCESSFUL BOX
C
          ELSE
           NSAVP=NPTS
           KPTS=NPTS+NX*NY*NZ
           IF(KPTS.GT.MAX_PTS)THEN
            PRINT *,'VMESH: MAX_PTS MUST BE AT LEAST: ',KPTS
            STOP
           END IF
           VOLBOX=0.0D0
           CORBOX=8*SIDE(2,1,JATOM)*SIDE(2,2,JATOM)*SIDE(2,3,JATOM)
           DO 600 IX=1,NX
            DO IY=1,NY
             DO IZ=1,NZ
              NPTS=NPTS+1
              R(1,NPTS)=RX(IX)
              R(2,NPTS)=RY(IY)
              R(3,NPTS)=RZ(IZ)
              DV(1,NPTS)=WX(IX)*WY(IY)*WZ(IZ)
              VOLBOX=VOLBOX+DV(1,NPTS)
              DV(1,NPTS)=DV(1,NPTS)*NUMBOX(JATOM)
              DV(2,NPTS)=1.0D0
             END DO
            END DO
  600      CONTINUE
           PRINT *,'NUMBER OF CANDIDATE POINTS:',(NPTS-NSAVP)
           IF((NPTS-NSAVP).GT.KILO)THEN
            PRINT *,'VMESH: KILO MUST BE AT LEAST: ',NPTS-NSAVP
            STOP
           END IF
C
C PURGE EQIVALENT POINTS
C
           DO IPTS=NSAVP+1,NPTS
            RSQR(IPTS-NSAVP)=R(1,IPTS)**2+R(2,IPTS)**2+R(3,IPTS)**2
           END DO
           DO 640 IPTS=NSAVP+1,NPTS
            IRED=IPTS-NSAVP
            IF(DV(2,IPTS) .GT. 0.0D0)THEN
             DO 630 JPTS=IPTS+1,NPTS
              JRED=JPTS-NSAVP
              IF ((ABS(RSQR(JRED)-RSQR(IRED)).LE.TOLER) .AND.
     &            (DV(2,JPTS) .GT. 0.0D0)) THEN
C
C CHECK FOR EQUIVALENCE
C
               DO IGRP=1,NGRP
                DIF=0.0D0
                DO J=1,3
                 RTMP=0.0D0
                 DO K=1,3
                  RTMP=RTMP+RMAT(K,J,IGRP)*R(K,JPTS)
                 END DO
                 DIF=DIF+ABS(RTMP-R(J,IPTS))
                END DO
                IF(DIF.LT.TOLER)GOTO 610
               END DO
               GOTO 620
  610          CONTINUE
               DV(1,IPTS)=DV(1,IPTS)+DV(1,JPTS)
               DV(2,JPTS)= -1.0D0
  620          CONTINUE
              END IF
  630        CONTINUE
            END IF
  640      CONTINUE
C
C GET RID OF EQUIVALENT POINTS
C
           KPTS=NPTS
           NPTS=NSAVP
           VOLBOX=0.0D0
           DO IPTS=NSAVP+1,KPTS
            IF(DV(2,IPTS) .GT. 0.0D0)THEN
             NPTS=NPTS+1
             R(1,NPTS)=R(1,IPTS)
             R(2,NPTS)=R(2,IPTS)
             R(3,NPTS)=R(3,IPTS)
             DV(1,NPTS)=DV(1,IPTS)
             VOLBOX=VOLBOX+DV(1,NPTS)
            END IF
           END DO
           ATMP=NUMBOX(JATOM)
           VOLBOX=VOLBOX/ATMP
           PRINT *,'FINISHED MESH FOR BOX ',JATOM,', NPTS= ',NPTS
           PRINT 8040,'VOLUME:',VOLBOX,'CORRECT:',CORBOX
          END IF
C
C CHECK IF WE ARE DONE WITH IATOM
C
          IF((JATOM.LT.NTOTAL).AND.LREPAIR)GOTO 570
         CONTINUE
  650   CONTINUE
        PRINT *,'INTERSTITIAL POINTS COMPLETE'
C
C SORT IDENTITY MEMBERS SO THAT SUCCESSIVE ONES ARE CLOSE
C
        DO 660 IIDENT=1,NIDENT-2
         ISTART=IIDENT+1
         IND1=0
         RMIN=1.0D30
         DO JIDENT=ISTART,NIDENT
          DIST=(CIDENT(1,IIDENT)-CIDENT(1,JIDENT))**2
     &        +(CIDENT(2,IIDENT)-CIDENT(2,JIDENT))**2
     &        +(CIDENT(3,IIDENT)-CIDENT(3,JIDENT))**2
          IF(DIST.LT.RMIN)THEN
           IND1=JIDENT
           RMIN=DIST
          END IF
         END DO
         IF(IND1.EQ.0)THEN
          PRINT *,'VMESH: SORTING ALGORITHM FAILED'
          STOP
         END IF
         DO I=1,3
          RTMP=CIDENT(I,ISTART)
          CIDENT(I,ISTART)=CIDENT(I,IND1)
          CIDENT(I,IND1)=RTMP
         END DO
  660   CONTINUE
C
C SETUP DV(2,IPTS)
C
        PRINT *,' '
        PRINT *,'SETTING UP ALTERNATE VOLUME ELEMENTS'
        NCUBE=0
        DO IIDENT=1,NIDENT
         KCUBE=MXCUBE-NCUBE
         CALL GASITES(3,CIDENT(1,IIDENT),KCUBE,CUBE(1,NCUBE+1))
         NCUBE=NCUBE+KCUBE
        END DO
C
C FIND CLOSEST ATOM TO EACH POINT AND SET UP DV(2,IPTS)
C
        VTOT=0.0D0
        DO 670 IPTS=1,NPTS
         DCLOS=1.0D30
         DO ICUBE=1,NCUBE
          DIST=(R(1,IPTS)-CUBE(1,ICUBE))**2+
     &         (R(2,IPTS)-CUBE(2,ICUBE))**2+
     &         (R(3,IPTS)-CUBE(3,ICUBE))**2
          DCLOS=MIN(DCLOS,DIST)
         END DO
         DV(2,IPTS)=DV(1,IPTS)/(DCLOS**1.5D0)
         VTOT=VTOT+DV(1,IPTS)
  670   CONTINUE
        PRINT 8040,'VOLUME:',VTOT,'EXPECTED:',EXPECTED
C
C MOVE POINTS AS CLOSE AS POSSIBLE TO AN IDENTITY MEMBER
C MAKE SURE THE POINT IS CLOSE ENOUGH TO THAT ATOM 
C
        RPIL2=RPILE**2
        CALL GTTIME(OT1)
        DO 710 IPTS=1,NPTS
         DCLOS=1.0D30
         DO 690 IGRP=1,NGRP
          DO I=1,3
           RX(I)=0.0D0
           DO J=1,3
            RX(I)=RX(I)+RMAT(J,I,IGRP)*R(J,IPTS)
           END DO
          END DO
          DO 680 IIDENT=1,NIDENT
           DIST=(RX(1)-CIDENT(1,IIDENT))**2+
     &          (RX(2)-CIDENT(2,IIDENT))**2+
     &          (RX(3)-CIDENT(3,IIDENT))**2
           IF(DIST.LT.DCLOS)THEN
            DCLOS=DIST
            XXX=RX(1)
            YYY=RX(2)
            ZZZ=RX(3)
            IF(DCLOS.LT.RPIL2)THEN
             ICLOSE(IPTS)=IIDENT
             GOTO 700
            END IF
           END IF
  680     CONTINUE
  690    CONTINUE
  700    CONTINUE
         R(1,IPTS)=XXX
         R(2,IPTS)=YYY
         R(3,IPTS)=ZZZ
  710   CONTINUE
C
C PUT POINTS BELONGING TO AN IDENTITY MEMBER AT THE BEGINNING
C
        VTOT=0.0D0
        JPTS=0
        DO 730 IIDENT=1,NIDENT
         DO 720 IPTS=JPTS+1,NPTS
          IF(ICLOSE(IPTS).EQ.IIDENT)THEN
           JPTS=JPTS+1
           ICLOSE(IPTS)=ICLOSE(JPTS)
           ICLOSE(JPTS)=IIDENT
           DO J=1,3
            RSAV=R(J,JPTS)
            R(J,JPTS)=R(J,IPTS)
            R(J,IPTS)=RSAV
           END DO
           DO J=1,2
            RSAV=DV(J,JPTS)
            DV(J,JPTS)=DV(J,IPTS)
            DV(J,IPTS)=RSAV
           END DO
           VTOT=VTOT+DV(1,JPTS)
          END IF
  720    CONTINUE
  730   CONTINUE
        PRINT *,'POINTS CLOSE TO IDENTITY MEMBERS: ',JPTS
        PRINT *,'TOTAL NUMBER OF POINTS:           ',NPTS
C
C NOW SORT THE POINTS THAT ARE NOT CLOSE TO AN IDENTITY MEMBER
C BUILD PILE OF ATOMS THAT ARE CLOSER THAN RPILE TO THE FIRST
C POINT OF THE PILE. AT THE SAME TIME, LOOK FOR THE POINT THAT
C IS CLOSEST TO THE FIRST POINT OF THE PILE, BUT DOES NOT BELONG
C TO THE PILE. THIS WILL BE THE STARTING POINT FOR THE NEXT PILE.
C      
        PRINT *,' '
        PRINT *,'REORDERING INTERSTITIAL POINTS'
  740   CONTINUE
         IF (JPTS.EQ.NPTS) GOTO 800 
         JPTS=JPTS+1
         VTOT=VTOT+DV(1,JPTS)
         DO I=1,3
          RX(I)=R(I,JPTS)
         END DO
         NNEXT=JPTS+1
         DCLOS=1.0D30
         IND=0
         DO 750 IPTS=JPTS+1,NPTS
          RSAV=(R(1,IPTS)-RX(1))**2 
     &        +(R(2,IPTS)-RX(2))**2 
     &        +(R(3,IPTS)-RX(3))**2 
          IF (RSAV.LT.RPIL2) THEN
           DO J=1,3
            RSAV=R(J,NNEXT)
            R(J,NNEXT)=R(J,IPTS)
            R(J,IPTS)=RSAV
           END DO
           DO J=1,2
            RSAV=DV(J,NNEXT)
            DV(J,NNEXT)=DV(J,IPTS)
            DV(J,IPTS)=RSAV
           END DO
           VTOT=VTOT+DV(1,NNEXT)
           IF (NNEXT.EQ.IND) IND=IPTS
           NNEXT=NNEXT+1
          ELSE
           IF (RSAV.LT.DCLOS) THEN
            DCLOS=RSAV
            IND=IPTS
           END IF
          END IF
  750    CONTINUE
C        PRINT *,'PILE COMPLETE, NPOINTS: ',NNEXT-JPTS,
C    &           ' LEFT: ',NPTS-NNEXT+1
C
C MOVE BEST POINT TO NEXT POSITION TO START WITH A POINT NOT TOO FAR
C AWAY FROM THE OLD PILE
C
         IF (IND.NE.0) THEN
          DO J=1,3
           RSAV=R(J,NNEXT)
           R(J,NNEXT)=R(J,IND)
           R(J,IND)=RSAV
          END DO
          DO J=1,2
           RSAV=DV(J,NNEXT)
           DV(J,NNEXT)=DV(J,IND)
           DV(J,IND)=RSAV
          END DO
         END IF
         JPTS=NNEXT-1
         GOTO 740
  800   CONTINUE
C       
C PRINT SOME STUFF
C
        CALL GTTIME(OT2)
        PRINT *,'TIME REORDERING IN VMESH: ',OT2-OT1
        PRINT 8040,'VOLUME:',VTOT,'EXPECTED:',EXPECTED
C
C LAST TEST: CHECK INTEGRATED CHARGE FOR OVERLAPPING ATOMIC DENSITIES
C AND ACCURACY OF OVERLAP MATRIX FOR CLUSTER SYSTEMS
C
        PRINT *,' '
        PRINT *,'TEST INTEGRATION FOR OVERLAPPING ATOMIC DENSITIES:'
        ALMIN=2*MAX(A1AT,A1IS)
        AFUDGE=4.0D0
        CHARGE=0.0D0
        ZTOT=0.0D0
        VCMIN= 1.0D30
        DO J=1,3
         VCMIN= MIN(VCMIN,BOXMOL(J,2)-BOXMOL(J,1))
        END DO
        RCOF= 0.1D0*ERRIS
        RCOF= RCUTOFF(0,ALMIN,RCOF)
        NTCEL= INT(RCOF/VCMIN)+1
        PRINT *,'NEIGHBOR CELL LIMIT: ',NTCEL
C
C LOOP OVER ALL ATOMS
C
        DO 820 INUC=1,NNUC
         PRINT *,'NUCLEUS ',INUC,' OF ',NNUC
         ALMAX=FACZ2*ZTEST(INUC)**2
         ALMAX=MAX(ALMAX,ALMIN)
         NALTST=2+NINT(LOG(ALMAX/ALMIN)/LOG(AFUDGE))
         ATMP=NALTST-1
         BETA=(ALMAX/ALMIN)**(1.0D0/ATMP)
         ZFRAC=ZTEST(INUC)/(ATMP+1.0D0)
         ZTOT=ZTOT+ZTEST(INUC)
C
C CLUSTER CASE
C
         IF (ISOLATED) THEN
          ALPHA=ALMIN
          DO 810 IALP=1,NALTST
           WALP=ZFRAC*(ALPHA/PI)**1.5D0
           DO IPTS=1,NPTS
            RTMP=(R(1,IPTS)-RNUC(1,INUC))**2
     &          +(R(2,IPTS)-RNUC(2,INUC))**2
     &          +(R(3,IPTS)-RNUC(3,INUC))**2
            CHARGE=CHARGE+DV(1,IPTS)*WALP*EXP(-ALPHA*RTMP)
           END DO
           ALPHA=ALPHA*BETA
  810     CONTINUE
C
C PERIODIC CASE
C
         ELSE 
          DO 1820 IX= -NTCEL*NLOOP(1),NTCEL*NLOOP(1)
          DO 1820 IY= -NTCEL*NLOOP(2),NTCEL*NLOOP(2)
          DO 1820 IZ= -NTCEL*NLOOP(3),NTCEL*NLOOP(3)
C
C GET SMALLEST POSSIBLE DISTANCE TO ORIGINAL UNIT CELL
C
           DOT= 0.0D0
           DO J=1,3
            TV(J)=RNUC(J,INUC)+IX*TVC(J,1)+IY*TVC(J,2)+IZ*TVC(J,3)
            IF (TV(J).LT.BOXMOL(J,1)) DOT= DOT+(TV(J)-BOXMOL(J,1))**2
            IF (TV(J).GT.BOXMOL(J,2)) DOT= DOT+(TV(J)-BOXMOL(J,2))**2
           END DO
           DOT= SQRT(DOT)
           ACCU= 0.1D0*ERRIS
           IF (DOT .LT. RCUTOFF(0,ALMIN,ACCU)) THEN
            ALPHA=ALMIN
            DO 1810 IALP=1,NALTST
             WALP=ZFRAC*(ALPHA/PI)**1.5D0
             DO IPTS=1,NPTS
              RTMP=(R(1,IPTS)-TV(1))**2
     &            +(R(2,IPTS)-TV(2))**2
     &            +(R(3,IPTS)-TV(3))**2
              CHARGE=CHARGE+DV(1,IPTS)*WALP*EXP(-ALPHA*RTMP)
C              RTST(IPTS)=              WALP*EXP(-ALPHA*RTMP)
             END DO
             ALPHA=ALPHA*BETA
 1810       CONTINUE
           END IF
 1820     CONTINUE
         END IF
  820   CONTINUE
        PRINT 8040,'INTEGRATED CHARGE:',CHARGE,'CORRECT:',ZTOT
C
C IF CLUSTER CALCULATION, CHECK OVERLAP MATRIX, ELSE
C ADD POINTS AT NUCLEUS WITH ZERO VOLUME (FOR NUCLEAR TOTAL ENERGY):
C
        IF (ISOLATED) THEN 
C        CALL TSTMSH
        ELSE
         DO I_ATOM=1,NNIDENT
          DO J=1,3
           TV(J)=RIDT(J,I_ATOM)
          ENDDO
          M_NUC=MXCUBE
          CALL GASITES(2,TV,M_NUC,CUBE)
          DO J_ATOM=1,M_NUC
           NPTS=NPTS+1
           IF(NPTS.GT.MAX_PTS)THEN
            PRINT*,'MAX_PTS IS TO SMALL'
            STOP
           END IF
           R(1,NPTS)=CUBE(1,J_ATOM)
           R(2,NPTS)=CUBE(2,J_ATOM)
           R(3,NPTS)=CUBE(3,J_ATOM)
           DV(1,NPTS)=0.0D0
          END DO
         END DO
         CLOSE(99)
        END IF
C       
C WRITE VMOLD AND LEAVE
C
        OPEN(99,FILE='VMOLD',FORM='UNFORMATTED',STATUS='UNKNOWN')
        REWIND(99)
        WRITE(99)NPTS,ICALC
        WRITE(99)(( R(J,I),J=1,3),I=1,NPTS)
        WRITE(99)((DV(J,I),J=1,1),I=1,NPTS)
                 DO I=1,NPTS
                 DVV(1,I)=DV(1,I)
                 END DO
        CLOSE(99)
  900   PRINT *,'LEAVING VMESH'
        PRINT *,' '
        RETURN
C
C FORMAT STUFF
C
 8010   FORMAT(3(1X,G20.14))
 8020   FORMAT(1X,A,3(1X,G15.8))
 8030   FORMAT(1X,A,1X,I5,2(1X,G15.8))
 8040   FORMAT(2(1X,A,1X,G20.14))
 8050   FORMAT(3(1X,A,1X,I6,1X))
 8060   FORMAT(3(1X,G20.14)/2(1X,G20.14))
 8070   FORMAT(1X,A,1X,I6,1X,A,1X,G20.14,1X,A,1X,I6)
       END
C
C
       SUBROUTINE CROSPR(X,Y,Z)
        IMPLICIT REAL*8 (A-H,O-Z)
        DIMENSION X(3),Y(3),Z(3) 
        Z(1)=X(2)*Y(3)-Y(2)*X(3)
        Z(2)=X(3)*Y(1)-Y(3)*X(1)
        Z(3)=X(1)*Y(2)-Y(1)*X(2)
       RETURN
       END 
C
C ******************************************************************
C
C RCUTOFF CALCULATES THE ALLOWED CUTOFF RADIUS FOR A TEST FUNCTION 
C F(R)= R**N * EXP(-AMIN*R**2) SO THAT 
C INTEGRAL(RCUTOFF->INFINITY)/INTEGRAL(0->INFINITY) = EPS
C
C N,AMIN,EPS: SEE ABOVE FORMULA
C
       FUNCTION RCUTOFF(N,AMIN,EPS)
        IMPLICIT REAL*8 (A-H,O-Z)
        SAVE
        DATA ACCU /5.0D-16/
        DATA ZERO /1.0D-30/
C
        IF (AMIN .LT. ZERO) THEN
         PRINT *,'RCUTOFF: AMIN IS TOO SMALL'
         CALL STOPIT
        END IF
C
C MACHINE ACCURACY
C
        CALL MACHEPS(SMALL)
        SMALL=10*SMALL
        SMALL=MAX(SMALL,ACCU)
        M=MAX(N,1)
        IF (MOD(M,2).NE.1) M=M+1
        ALRC=1.0D0/AMIN
        AL2RC=0.5D0*ALRC 
C
C INTEGRAL(0->INFINITY)
C
        TOTI=AL2RC
        DO I=3,M,2
         TOTI=(I-1)*AL2RC*TOTI
        END DO
        TOTI=TOTI*EPS
C
C ITERATION
C
        R=SQRT((1.0D0*(M-1)-LOG(EPS))*ALRC)
        ITER=0
  110   CONTINUE    
         ROLD=R
         ITER=ITER+1
         IF (ITER .GT. 100*M) THEN
          PRINT *,'RCUTOFF: ITERATION FAILURE'
          CALL STOPIT
         END IF
         RSQR=R*R
         FAC=EXP(-AMIN*RSQR)
         ACTI=AL2RC*FAC
         RPOW=FAC
         DO I=3,M,2
          RPOW=RPOW*RSQR
          ACTI=AL2RC*(RPOW+(I-1)*ACTI)
         END DO
         DRVI= -RPOW*R
         R=ROLD-(ACTI-TOTI)/DRVI
         IF (R .LT. 0.0D0)  R=ROLD-5.0D0
         IF (R .GT. 2*ROLD) R=ROLD+5.0D0
         IF (ABS(R-ROLD) .LE. SMALL*ABS(ROLD)) GOTO 120
         GOTO 110
  120   CONTINUE
        RCUTOFF= R
        RETURN
       END
